apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jcolqpi4q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jcolqpi4q-go 
  name: jcolqpi4q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jcolqpi4q-go 
